
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;

        # IMPORTANT: use absolute path that matches the app container
        fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /usr/share/nginx/html/public;

        fastcgi_pass app:9000;
    }
}
