#!/bin/bash
set -e

main() {
    if [ "$IS_WORKER" = "true" ]; then
        exec "$@"
    fi

    prepare_file_permissions
    prepare_storage

    exec "$@"
}

prepare_file_permissions() {
    chmod a+x /usr/share/nginx/html/artisan || true
    chown -R www-data:www-data /usr/share/nginx/html/storage /usr/share/nginx/html/bootstrap/cache || true
}

prepare_storage() {
    mkdir -p /usr/share/nginx/html/storage/framework/cache/data
    mkdir -p /usr/share/nginx/html/storage/framework/sessions
    mkdir -p /usr/share/nginx/html/storage/framework/views

    chown -R www-data:www-data /usr/share/nginx/html/storage
    chmod -R 775 /usr/share/nginx/html/storage

    php /usr/share/nginx/html/artisan storage:link || true
}

main "$@"
