#!/bin/sh
set -e

APP=/var/www

prepare() {
    mkdir -p $APP/storage/framework/{cache,sessions,views}

    chown -R www-data:www-data $APP/storage $APP/bootstrap/cache || true
    chmod -R 775 $APP/storage || true

    php $APP/artisan storage:link || true
}

prepare

exec "$@"
